language: android

jdk:
 - oraclejdk7

android:
  components:
    - build-tools-20.0.0
    - android-19
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

notifications:
  email: false